const matches = [
  {
    _id: 0,
    round: 1,
    team1: "Gremio",
    team2: "Santos",
    date: "2023-04-15",
    place: "Alfredo Jaconi",
  },
  {
    _id: 1,
    round: 2,
    team1: "Cruzeiro",
    team2: "Gremio",
    date: "2023-04-22",
    place: "Independencia",
  },
  {
    _id: 2,
    round: 3,
    team1: "Cuiaba",
    team2: "Gremio",
    date: "2023-04-30",
    place: "Arena Pantanal",
  },
  {
    _id: 3,
    round: 4,
    team1: "Gremio",
    team2: "Bragantino",
    date: "2023-05-07",
    place: "Arena do Gremio",
  },
  {
    _id: 4,
    round: 5,
    team1: "Palmeiras",
    team2: "Gremio",
    date: "2023-05-10",
    place: "Allianz Parque",
  },
  {
    _id: 5,
    round: 6,
    team1: "Gremio",
    team2: "Fortaleza",
    date: "2023-05-14",
    place: "Arena do Gremio",
  },
  {
    _id: 6,
    round: 7,
    team1: "Gremio",
    team2: "Inter-RS",
    date: "2023-05-21",
    place: "Arena do Gremio",
  },
  {
    _id: 7,
    round: 8,
    team1: "Athletico",
    team2: "Gremio",
    date: "2023-05-28",
    place: "Arena da Baixada",
  },
  {
    _id: 8,
    round: 9,
    team1: "Gremio",
    team2: "Sao Paulo",
    date: "2023-06-04",
    place: "Arena do Gremio",
  },
  {
    _id: 9,
    round: 10,
    team1: "Flamengo",
    team2: "Gremio",
    date: "2023-06-11",
    place: "Maracana",
  },
  {
    _id: 10,
    round: 11,
    team1: "Gremio",
    team2: "America",
    date: "2023-06-21",
    place: "Arena do Gremio",
  },
  {
    _id: 11,
    round: 12,
    team1: "Gremio",
    team2: "Coritiba",
    date: "2023-06-25",
    place: "Arena do Gremio",
  },
  {
    _id: 12,
    round: 13,
    team1: "Bahia",
    team2: "Gremio",
    date: "2023-07-02",
    place: "Arena Fonte Nova",
  },
  {
    _id: 13,
    round: 14,
    team1: "Gremio",
    team2: "Botafogo",
    date: "2023-07-09",
    place: "Arena do Gremio",
  },
  {
    _id: 14,
    round: 15,
    team1: "Corinthians",
    team2: "Gremio",
    date: "2023-07-16",
    place: "Arena Corinthians",
  },
  {
    _id: 15,
    round: 16,
    team1: "Gremio",
    team2: "Atletico-MG",
    date: "2023-07-23",
    place: "Arena Corinthians",
  },
  {
    _id: 16,
    round: 17,
    team1: "Goias",
    team2: "Gremio",
    date: "2023-07-30",
    place: "Serra Dourada",
  },
  {
    _id: 17,
    round: 18,
    team1: "Vasco",
    team2: "Gremio",
    date: "2023-08-02",
    place: "Sao Januario",
  },
  {
    _id: 18,
    round: 18,
    team1: "Gremio",
    team2: "Fluminense",
    date: "2023-08-06",
    place: "Arena do Gremio",
  },
];

export default matches;
